version: "3.4"
services:

    postgres:
      image: postgres:9.6-alpine
      container_name: postgres
      working_dir: /application
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
       - "5432:5432"
      environment:
        - POSTGRES_USER=pguser
        - POSTGRES_PASSWORD=
