<<<<<<< HEAD
version: "3.8"
services:

  postgres:
    image: postgres:12.4-alpine
    container_name: postgres
    working_dir: /application
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
=======
version: "3.4"
services:

    postgres:
      image: postgres:9.6-alpine
      container_name: postgres
      working_dir: /application
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
       - "5432:5432"
      environment:
        - POSTGRES_USER=pguser
        - POSTGRES_PASSWORD=
>>>>>>> cdceba2b11863615b59adf485c9b7e9ba2726f16
